spring:
  application:
    name: BackEnd
  datasource:
      url: jdbc:sqlserver://db:1433;databaseName=master;encrypt=false;trustServerCertificate=true
      username: sa
      password: yourStrong(!)Password
  jpa:
    show-sql: true
    database: sqlserver
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: update
